### ISSUE TITLE
Lock down html5lib dependency

### ISSUE THREAD

**Issue by dentarg** [dentarg/pynik#36]
```
$ dotenv python offline_tester.py
Traceback (most recent call last):
  File "offline_tester.py", line 2, in <module>
    import plugin_handler
  File "/Users/dentarg/Dropbox/code/projects/pynik/min_pynik/plugin_handler.py", line 10, in <module>
    from plugins import *
  File "/Users/dentarg/Dropbox/code/projects/pynik/min_pynik/plugins/title_reader.py", line 12, in <module>
    import bleach
  File "/usr/local/lib/python2.7/site-packages/bleach/__init__.py", line 14, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named sanitizer
```

See https://github.com/mozilla/bleach/issues/212

**Comment by dentarg** [comment]
Also https://github.com/html5lib/html5lib-python/issues/277
